### ISSUE TITLE
Maybe an error in the batch_generator.py

### ISSUE THREAD

**Issue by CNchence** [opeide/CNN-3D-pose-estimation#1]
There may be an error in the batch_generator.py, in the function: _get_puller, anchor_obj can't be a key for the self.db.         By the way, what version of tensorflow are you using and how do you start the training program?

**Comment by opeide** [comment]
There were definitely many errors at the time you forked it, as I was figuring out how the custom estimators were supposed to work, and how training input should be received. What you pointed out is however not an error, the code is just more unreadable than I had hoped. Still some work to be done on other parts of the project.

**Comment by CNchence** [comment]
Thanks for your answer, I have found that the cause of the error is because of my windows environment, resulting in the file path is not the same as under linux (\\ vs /).
